// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Slipless",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Slipless",
            targets: ["AppModule"],
            bundleIdentifier: "com.robertnegel.OneLess",
            teamIdentifier: "7B8JYS7JC8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "App/Config/SubmissionInfo.plist"
        )
    ],
    targets: [
        .target(
            name: "SliplessCore",
            path: "App",
            exclude: [
                "Config",
                "Resources",
                "SliplessApp.swift",
                "Widgets"
            ]
        ),
        .executableTarget(
            name: "AppModule",
            dependencies: ["SliplessCore"],
            path: "App",
            sources: [
                "SliplessApp.swift"
            ],
            resources: [
                .process("Resources")
            ]
        ),
        .testTarget(
            name: "AppModuleTests",
            dependencies: ["SliplessCore"],
            path: "Tests"
        )
    ]
)